
DROP TABLE transaction CASCADE;
DROP TABLE option CASCADE;
DROP TABLE mechanic CASCADE;
DROP TABLE manager CASCADE;
DROP TABLE contract CASCADE;
DROP TABLE car CASCADE;
DROP TABLE salesman CASCADE;
DROP TABLE employee CASCADE;
DROP TABLE customer CASCADE;
DROP TABLE carmanufacturer CASCADE;
DROP TABLE branchoffice CASCADE;
DROP TABLE features CASCADE;
DROP TABLE maintenance CASCADE;