INSERT INTO carmanufacturer  VALUES ('560072', 'Toyota', '7733 Meadow Run Way', 'Toronto', 'ON');
INSERT INTO carmanufacturer  VALUES ('363168', 'Toyota', '9391 Winding Creek Circle', 'Orleans', 'ON');
INSERT INTO carmanufacturer  VALUES ('654417', 'Toyota', '2662 Van Tassel Lane', 'Markham', 'ON');
INSERT INTO carmanufacturer  VALUES ('130662', 'Toyota', '4310 Oryan Trail', 'Ottawa', 'ON');
INSERT INTO carmanufacturer  VALUES ('130321', 'Toyota', '2733 Last Arrow Cove', 'Vancouver', 'BC');
INSERT INTO carmanufacturer  VALUES ('661660', 'Toyota', '1411 Donnington Lane', 'Montreal', 'QC');
INSERT INTO carmanufacturer  VALUES ('623815', 'Toyota', '4217 Still Meadow Circle', 'Edmonton', 'AB');
INSERT INTO carmanufacturer  VALUES ('886743', 'Toyota', '3148 Redwood Place Drive', 'Victoria', 'BC');
INSERT INTO carmanufacturer  VALUES ('277923', 'Toyota', '3840 Dian Avenue', 'London', 'ON');
INSERT INTO carmanufacturer  VALUES ('274707', 'Toyota', '7115 Deerfield Parkway', 'Moncton', 'NB');
INSERT INTO carmanufacturer  VALUES ('445039', 'Toyota', '3068 Mcclellan Drive', 'Richmond Hill', 'ON');
INSERT INTO carmanufacturer  VALUES ('397838', 'Toyota', '3631 Holcombe Lane', 'Halifax', 'NS');
INSERT INTO carmanufacturer  VALUES ('911957', 'Volkswagen', '368 Turkey Way', 'Toronto', 'ON');
INSERT INTO carmanufacturer  VALUES ('906152', 'Volkswagen', '6036 Lockridge Circle', 'Orleans', 'ON');
INSERT INTO carmanufacturer  VALUES ('440682', 'Volkswagen', '4279 Stamford Trail', 'Markham', 'ON');
INSERT INTO carmanufacturer  VALUES ('237609', 'Volkswagen', '6990 Chesley Trail', 'Ottawa', 'ON');
INSERT INTO carmanufacturer  VALUES ('628898', 'Volkswagen', '3449 Cedarwood Circle', 'Vancouver', 'BC');
INSERT INTO carmanufacturer  VALUES ('905524', 'Volkswagen', '4375 Eagle Branch Cove', 'Montreal', 'QC');
INSERT INTO carmanufacturer  VALUES ('182511', 'Volkswagen', '9893 Brook Bridge Trail', 'Edmonton', 'AB');
INSERT INTO carmanufacturer  VALUES ('806181', 'Volkswagen', '8843 Rocky Hollow Lane', 'Victoria', 'BC');
INSERT INTO carmanufacturer  VALUES ('405460', 'Volkswagen', '8799 Green Forest Parkway', 'London', 'ON');
INSERT INTO carmanufacturer  VALUES ('362223', 'Volkswagen', '9250 Laurie Street', 'Moncton', 'NB');
INSERT INTO carmanufacturer  VALUES ('324213', 'Volkswagen', '3581 Nottingham Oaks Parkway', 'Richmond Hill', 'ON');
INSERT INTO carmanufacturer  VALUES ('784375', 'Volkswagen', '5173 Threadneedle Circle', 'Halifax', 'NS');
INSERT INTO carmanufacturer  VALUES ('900648', 'Nissan', '4889 Pebblebrook Avenue', 'Toronto', 'ON');
INSERT INTO carmanufacturer  VALUES ('383474', 'Nissan', '7283 Hidden Oaks Trail', 'Orleans', 'ON');
INSERT INTO carmanufacturer  VALUES ('472960', 'Nissan', '6579 Newsum Lane', 'Markham', 'ON');
INSERT INTO carmanufacturer  VALUES ('382386', 'Nissan', '1300 Neshoba Trace Drive', 'Ottawa', 'ON');
INSERT INTO carmanufacturer  VALUES ('805439', 'Nissan', '2820 Wood Briar Cove', 'Vancouver', 'BC');
INSERT INTO carmanufacturer  VALUES ('278976', 'Nissan', '3221 William Lane', 'Montreal', 'QC');
INSERT INTO carmanufacturer  VALUES ('554987', 'Nissan', '2387 Valley Crest Circle', 'Edmonton', 'AB');
INSERT INTO carmanufacturer  VALUES ('205114', 'Nissan', '4098 Rainbow Trail', 'Victoria', 'BC');
INSERT INTO carmanufacturer  VALUES ('416835', 'Nissan', '2888 Magnolia Tree Avenue', 'London', 'ON');
INSERT INTO carmanufacturer  VALUES ('196478', 'Nissan', '8550 Kahlden Circle', 'Moncton', 'NB');
INSERT INTO carmanufacturer  VALUES ('929332', 'Nissan', '7843 Ingberg Street', 'Richmond Hill', 'ON');
INSERT INTO carmanufacturer  VALUES ('126881', 'Nissan', '3183 Londonderry Drive', 'Halifax', 'NS');
INSERT INTO carmanufacturer  VALUES ('661534', 'BMW', '8430 Juno Circle', 'Toronto', 'ON');
INSERT INTO carmanufacturer  VALUES ('437394', 'BMW', '9042 Ilo Cove', 'Orleans', 'ON');
INSERT INTO carmanufacturer  VALUES ('716173', 'BMW', '6149 Commodore Drive', 'Markham', 'ON');
INSERT INTO carmanufacturer  VALUES ('757106', 'BMW', '2278 Blue Grass Parkway', 'Ottawa', 'ON');
INSERT INTO carmanufacturer  VALUES ('767538', 'BMW', '3611 Apple Valley Lane', 'Vancouver', 'BC');
INSERT INTO carmanufacturer  VALUES ('814180', 'BMW', '2222 Lockridge Parkway', 'Montreal', 'QC');
INSERT INTO carmanufacturer  VALUES ('258987', 'BMW', '4697 Wren Trail', 'Edmonton', 'AB');
INSERT INTO carmanufacturer  VALUES ('583046', 'BMW', '8322 Keats Parkway', 'Victoria', 'BC');
INSERT INTO carmanufacturer  VALUES ('594377', 'BMW', '3872 Staloch Trail', 'London', 'ON');
INSERT INTO carmanufacturer  VALUES ('588003', 'BMW', '6856 Mckusick Avenue', 'Moncton', 'NB');
INSERT INTO carmanufacturer  VALUES ('398621', 'BMW', '8389 Oak Bend Cove', 'Richmond Hill', 'ON');
INSERT INTO carmanufacturer  VALUES ('737726', 'BMW', '2484 Oren Circle', 'Halifax', 'NS');
INSERT INTO carmanufacturer  VALUES ('890097', 'Mercedes', '8172 Chertsy Circle', 'Toronto', 'ON');
INSERT INTO carmanufacturer  VALUES ('503023', 'Mercedes', '2168 Mill Lane', 'Orleans', 'ON');
INSERT INTO carmanufacturer  VALUES ('806941', 'Mercedes', '3315 Bayou Knoll Street', 'Markham', 'ON');
INSERT INTO carmanufacturer  VALUES ('909941', 'Mercedes', '2963 Queens Way', 'Ottawa', 'ON');
INSERT INTO carmanufacturer  VALUES ('547887', 'Mercedes', '1094 Barryknoll Drive', 'Vancouver', 'BC');
INSERT INTO carmanufacturer  VALUES ('841829', 'Mercedes', '3436 Goswell Cove', 'Montreal', 'QC');
INSERT INTO carmanufacturer  VALUES ('351350', 'Mercedes', '9068 Pyron Oaks Circle', 'Edmonton', 'AB');
INSERT INTO carmanufacturer  VALUES ('614747', 'Mercedes', '4145 Queens Trail', 'Victoria', 'BC');
INSERT INTO carmanufacturer  VALUES ('138665', 'Mercedes', '7422 Wolf Bend Parkway', 'London', 'ON');
INSERT INTO carmanufacturer  VALUES ('691215', 'Mercedes', '1273 Edenfield Parkway', 'Moncton', 'NB');
INSERT INTO carmanufacturer  VALUES ('535767', 'Mercedes', '297 Germantown Cove', 'Richmond Hill', 'ON');
INSERT INTO carmanufacturer  VALUES ('282647', 'Mercedes', '5081 Edenfield Drive', 'Halifax', 'NS');
INSERT INTO carmanufacturer  VALUES ('814506', 'Lexus', '8021 Greenwood Cove', 'Toronto', 'ON');
INSERT INTO carmanufacturer  VALUES ('392265', 'Lexus', '5351 Steeplegate Drive', 'Orleans', 'ON');
INSERT INTO carmanufacturer  VALUES ('250521', 'Lexus', '8562 Ravensdale Parkway', 'Markham', 'ON');
INSERT INTO carmanufacturer  VALUES ('319122', 'Lexus', '9641 Green Downs Circle', 'Ottawa', 'ON');
INSERT INTO carmanufacturer  VALUES ('242783', 'Lexus', '5014 Chestnut Way', 'Vancouver', 'BC');
INSERT INTO carmanufacturer  VALUES ('874657', 'Lexus', '4900 Washington Drive', 'Montreal', 'QC');
INSERT INTO carmanufacturer  VALUES ('111607', 'Lexus', '8353 Fords Station Avenue', 'Edmonton', 'AB');
INSERT INTO carmanufacturer  VALUES ('254914', 'Lexus', '84 Ottawa Parkway', 'Victoria', 'BC');
INSERT INTO carmanufacturer  VALUES ('464724', 'Lexus', '5454 Nolan Circle', 'London', 'ON');
INSERT INTO carmanufacturer  VALUES ('685413', 'Lexus', '3787 Hunters Den Lane', 'Moncton', 'NB');
INSERT INTO carmanufacturer  VALUES ('853878', 'Lexus', '7323 Station Hill Lane', 'Richmond Hill', 'ON');
INSERT INTO carmanufacturer  VALUES ('907059', 'Lexus', '6904 Sleepy Hollow Circle', 'Halifax', 'NS');
INSERT INTO carmanufacturer  VALUES ('881547', 'Range Rover', '6968 Appaloosa Street', 'Toronto', 'ON');
INSERT INTO carmanufacturer  VALUES ('264866', 'Range Rover', '2477 Honeye Circle', 'Orleans', 'ON');
INSERT INTO carmanufacturer  VALUES ('398536', 'Range Rover', '7850 Shadeley Cove', 'Markham', 'ON');
INSERT INTO carmanufacturer  VALUES ('694223', 'Range Rover', '366 Bison Circle', 'Ottawa', 'ON');
INSERT INTO carmanufacturer  VALUES ('203148', 'Range Rover', '8242 Capital Way', 'Vancouver', 'BC');
INSERT INTO carmanufacturer  VALUES ('173340', 'Range Rover', '9131 Nolan Circle', 'Montreal', 'QC');
INSERT INTO carmanufacturer  VALUES ('122199', 'Range Rover', '5985 William Circle', 'Edmonton', 'AB');
INSERT INTO carmanufacturer  VALUES ('124369', 'Range Rover', '8969 Ashford Forest Lane', 'Victoria', 'BC');
INSERT INTO carmanufacturer  VALUES ('824765', 'Range Rover', '8856 Waterleaf Lane', 'London', 'ON');
INSERT INTO carmanufacturer  VALUES ('614064', 'Range Rover', '2964 Ashford Forest Street', 'Moncton', 'NB');
INSERT INTO carmanufacturer  VALUES ('667797', 'Range Rover', '930 Crooked Creek Avenue', 'Richmond Hill', 'ON');
INSERT INTO carmanufacturer  VALUES ('334862', 'Range Rover', '9299 Ole Pike Cove', 'Halifax', 'NS');
INSERT INTO carmanufacturer  VALUES ('272381', 'Audi', '7395 Lakeside Way', 'Toronto', 'ON');
INSERT INTO carmanufacturer  VALUES ('746060', 'Audi', '6991 Sibelius Lane', 'Orleans', 'ON');
INSERT INTO carmanufacturer  VALUES ('180958', 'Audi', '4853 Tamerlane Drive', 'Markham', 'ON');
INSERT INTO carmanufacturer  VALUES ('558393', 'Audi', '5094 Woodlane Parkway', 'Ottawa', 'ON');
INSERT INTO carmanufacturer  VALUES ('918280', 'Audi', '9297 Stone Walk Street', 'Vancouver', 'BC');
INSERT INTO carmanufacturer  VALUES ('669552', 'Audi', '6357 Old Mill Way', 'Montreal', 'QC');
INSERT INTO carmanufacturer  VALUES ('260921', 'Audi', '3047 Kimdale Avenue', 'Edmonton', 'AB');
INSERT INTO carmanufacturer  VALUES ('763404', 'Audi', '4521 Appaloosa Trail', 'Victoria', 'BC');
INSERT INTO carmanufacturer  VALUES ('136813', 'Audi', '3254 River Reach Way', 'London', 'ON');
INSERT INTO carmanufacturer  VALUES ('923006', 'Audi', '1808 Olive Cove', 'Moncton', 'NB');
INSERT INTO carmanufacturer  VALUES ('368248', 'Audi', '9447 Keswick Cove', 'Richmond Hill', 'ON');
INSERT INTO carmanufacturer  VALUES ('889931', 'Audi', '5378 Maize Drive', 'Halifax', 'NS');
INSERT INTO carmanufacturer  VALUES ('273060', 'Honda', '3194 Laurie Trail', 'Toronto', 'ON');
INSERT INTO carmanufacturer  VALUES ('705876', 'Honda', '9237 Tuenge Circle', 'Orleans', 'ON');
INSERT INTO carmanufacturer  VALUES ('902594', 'Honda', '1396 William Avenue', 'Markham', 'ON');
INSERT INTO carmanufacturer  VALUES ('257587', 'Honda', '2414 Pinerock Lane', 'Ottawa', 'ON');
INSERT INTO carmanufacturer  VALUES ('551239', 'Honda', '9747 Thorncroft Cove', 'Vancouver', 'BC');
INSERT INTO carmanufacturer  VALUES ('518476', 'Honda', '6725 Grenville Avenue', 'Montreal', 'QC');
INSERT INTO carmanufacturer  VALUES ('638542', 'Honda', '6899 Weeping Willow Way', 'Edmonton', 'AB');
INSERT INTO carmanufacturer  VALUES ('558585', 'Honda', '276 Wildpines Lane', 'Victoria', 'BC');
INSERT INTO carmanufacturer  VALUES ('896570', 'Honda', '8726 Pridalea Circle', 'London', 'ON');
INSERT INTO carmanufacturer  VALUES ('349661', 'Honda', '941 Pangbourne Parkway', 'Moncton', 'NB');
INSERT INTO carmanufacturer  VALUES ('362286', 'Honda', '4645 Comely Lane', 'Richmond Hill', 'ON');
INSERT INTO carmanufacturer  VALUES ('266361', 'Honda', '2167 Blackberry Ridge Drive', 'Halifax', 'NS');
INSERT INTO carmanufacturer  VALUES ('195153', 'Chevrolet', '6120 Wood Creek Lane', 'Toronto', 'ON');
INSERT INTO carmanufacturer  VALUES ('725100', 'Chevrolet', '6072 Mikeyair Way', 'Orleans', 'ON');
INSERT INTO carmanufacturer  VALUES ('129640', 'Chevrolet', '8650 Stout Trail', 'Markham', 'ON');
INSERT INTO carmanufacturer  VALUES ('868844', 'Chevrolet', '6250 Swenson Avenue', 'Ottawa', 'ON');
INSERT INTO carmanufacturer  VALUES ('299638', 'Chevrolet', '703 Duckhorn Trail', 'Vancouver', 'BC');
INSERT INTO carmanufacturer  VALUES ('642369', 'Chevrolet', '7431 Donnington Trail', 'Montreal', 'QC');
INSERT INTO carmanufacturer  VALUES ('589812', 'Chevrolet', '2912 Panama Lane', 'Edmonton', 'AB');
INSERT INTO carmanufacturer  VALUES ('716519', 'Chevrolet', '5032 Benson Circle', 'Victoria', 'BC');
INSERT INTO carmanufacturer  VALUES ('222442', 'Chevrolet', '5721 Donnington Lane', 'London', 'ON');
INSERT INTO carmanufacturer  VALUES ('822340', 'Chevrolet', '9198 Olive Trail', 'Moncton', 'NB');
INSERT INTO carmanufacturer  VALUES ('744724', 'Chevrolet', '2636 Riverlace Circle', 'Richmond Hill', 'ON');
INSERT INTO carmanufacturer  VALUES ('487315', 'Chevrolet', '6134 Frontage Lane', 'Halifax', 'NS');
INSERT INTO carmanufacturer  VALUES ('522501', 'Kia', '1985 Kersh Trail', 'Toronto', 'ON');
INSERT INTO carmanufacturer  VALUES ('385383', 'Kia', '9221 Falling Leaf Avenue', 'Orleans', 'ON');
INSERT INTO carmanufacturer  VALUES ('548463', 'Kia', '2343 Mardite Avenue', 'Markham', 'ON');
INSERT INTO carmanufacturer  VALUES ('559080', 'Kia', '7270 Elm Drive', 'Ottawa', 'ON');
INSERT INTO carmanufacturer  VALUES ('615193', 'Kia', '9561 Wickchester Lane', 'Vancouver', 'BC');
INSERT INTO carmanufacturer  VALUES ('522376', 'Kia', '5776 Fords Station Street', 'Montreal', 'QC');
INSERT INTO carmanufacturer  VALUES ('648902', 'Kia', '982 Crossroads Circle', 'Edmonton', 'AB');
INSERT INTO carmanufacturer  VALUES ('390322', 'Kia', '6936 Kelvin Circle', 'Victoria', 'BC');
INSERT INTO carmanufacturer  VALUES ('815644', 'Kia', '829 Crestwood Parkway', 'London', 'ON');
INSERT INTO carmanufacturer  VALUES ('705309', 'Kia', '2380 Shady Creek Street', 'Moncton', 'NB');
INSERT INTO carmanufacturer  VALUES ('408591', 'Kia', '5449 Baytown Drive', 'Richmond Hill', 'ON');
INSERT INTO carmanufacturer  VALUES ('210533', 'Kia', '6732 Thistlewood Avenue', 'Halifax', 'NS');
INSERT INTO carmanufacturer  VALUES ('723909', 'Hyundai', '5583 Wilchester Way', 'Toronto', 'ON');
INSERT INTO carmanufacturer  VALUES ('109538', 'Hyundai', '8271 Honeye Avenue', 'Orleans', 'ON');
INSERT INTO carmanufacturer  VALUES ('809147', 'Hyundai', '7662 Norwich Lane', 'Markham', 'ON');
INSERT INTO carmanufacturer  VALUES ('369550', 'Hyundai', '6483 Wolf Park Street', 'Ottawa', 'ON');
INSERT INTO carmanufacturer  VALUES ('985207', 'Hyundai', '4063 Ottawa Circle', 'Vancouver', 'BC');
INSERT INTO carmanufacturer  VALUES ('668424', 'Hyundai', '1966 Abbott Cove', 'Montreal', 'QC');
INSERT INTO carmanufacturer  VALUES ('455712', 'Hyundai', '1145 Stillbrook Cove', 'Edmonton', 'AB');
INSERT INTO carmanufacturer  VALUES ('651762', 'Hyundai', '4174 Overlook Avenue', 'Victoria', 'BC');
INSERT INTO carmanufacturer  VALUES ('687774', 'Hyundai', '1146 Dundee Avenue', 'London', 'ON');
INSERT INTO carmanufacturer  VALUES ('362996', 'Hyundai', '3730 Bow String Way', 'Moncton', 'NB');
INSERT INTO carmanufacturer  VALUES ('516863', 'Hyundai', '6308 Wickchester Cove', 'Richmond Hill', 'ON');
INSERT INTO carmanufacturer  VALUES ('270569', 'Hyundai', '4423 Maple Shadow Street', 'Halifax', 'NS');
